sync_bytes: ["aa", "44", "12"]
header_structure:
  - name: header_length
    offset: 3
    size: 1
    encode: int
  - name: message_id
    offset: 4
    size: 2
    encode: int
  - name: message_type
    offset: 6
    size: 1
  - name: port_address
    offset: 7
    size: 1
  - name: message_length
    offset: 8
    size: 2
    encode: int
  - name: sequence
    offset: 10
    size: 2
  - name: idle_time
    offset: 12
    size: 1
    encode: int
  - name: time_status
    offset: 13
    size: 1
    encode: int
  - name: week
    offset: 14
    size: 2
    encode: int
  - name: ms
    offset: 16
    size: 4
    encode: int
  - name: receiver_status
    offset: 20
    size: 4
  - name: reserved
    offset: 24
    size: 2
  - name: receiver_s/w_version
    offset: 26
    size: 2
    encode: int
payload:
  size_from_header_field: message_length
  offset: 28
  messages:
    message_id:
      43:
        name: range
        fields:
          - name: num_observers
            offset: 0
            size: 4
          - name: prn
            offset: 4
            size: 2
          - name: glofreq
            offset: 6
            size: 2
          - name: psr
            offset: 8
            size: 8
          - name: psr_std
            offset: 16
            size: 4
          - name: adr
            offset: 20
            size: 8
          - name: adr_std
            offset: 28
            size: 4
          - name: dopp
            offset: 32
            size: 4
          - name: c_no
            offset: 36
            size: 4
          - name: locktime
            offset: 40
            size: 4
          - name: chtrstatus
            offset: 44
            size: 4
