sync_bytes: ["aa", "44", "12"]
header_structure:
  - name: header_length
    offset: 3
    size: 1
    encode: int
  - name: message_id
    offset: 4
    size: 2
    encode: int
  - name: message_type
    offset: 6
    size: 1
  - name: port_address
    offset: 7
    size: 1
  - name: message_length
    offset: 8
    size: 2
    encode: int
  - name: sequence
    offset: 10
    size: 2
  - name: idle_time
    offset: 12
    size: 1
    encode: int
  - name: time_status
    offset: 13
    size: 1
    encode: int
  - name: week
    offset: 14
    size: 2
    encode: int
  - name: ms
    offset: 16
    size: 4
    encode: int
  - name: receiver_status
    offset: 20
    size: 4
  - name: reserved
    offset: 24
    size: 2
  - name: receiver_s/w_version
    offset: 26
    size: 2
    encode: int
payload:
  size_from_header_field: message_length
  offset: 28
  messages:
    43:
      name: range
      fields:
        num_observers:
          offset: 0
          size: 4
          encode: int
        prn:
          offset: 4
          size: 2
          encode: int
        glofreq:
          offset: 6
          size: 2
          encode: int
        psr:
          offset: 8
          size: 8
        psr_std:
          offset: 16
          size: 4
        adr:
          offset: 20
          size: 8
        adr_std:
          offset: 28
          size: 4
        dopp:
          offset: 32
          size: 4
        c_no:
          offset: 36
          size: 4
        locktime:
          offset: 40
          size: 4
          encode: int
        chtrstatus:
          offset: 44
          size: 4
          encode: int
    973:
      name: raw_sbas_subframe
      fields:
        decode_num:
          offset: 0
          size: 4
          encode: int
        prn:
          offset: 4
          size: 4
          encode: int
        subframe_id:
          offset: 8
          size: 4
          encode: int
        data:
          offset: 12
          size: 32
    1306:
      name: front_end_data
      fields:
        num_of_AGC_status:
          offset: 0
          size: 4
        ul_my_front_end:
          offset: 4
          size: 4
        ul_time_stamp:
          offset: 8
          size: 4
          encode: int
        b_my_calibrated:
          offset: 12
          size: 4
        ul_my_adjust_mode:
          offset: 16
          size: 4
        ul_my_adjust_rate:
          offset: 20
          size: 4
        ul_my_pulse_width:
          offset: 24
          size: 4
        ul_my_modulus:
          offset: 28
          size: 4
        e_my_range:
          offset: 32
          size: 4
        d_my_DC_offset:
          offset: 36
          size: 8 
        d_my_PDF_error:
          offset: 44
          size: 8
        ad_my_pdf:
          offset: 52
          size: 48
    25:
      name: raw_gps_subframe
      fields:
        decode_num:
          offset: 0
          size: 4
          encode: int
        prn:
          offset: 4
          size: 4
          encode: int
        subframe_id:
          offset: 8
          size: 4
          encode: int
        data:
          offset: 12
          size: 32
        chan:
          offset: 44
          size: 4
          encode: int
        crc:
          offset: 48
          size: 4
    41:
      name: raw_ephem
      fields:
        prn:
          offset: 0
          size: 4
        ref_week:
          offset: 4
          size: 4
        ref_secs:
          offset: 8
          size: 4
        subframe_1:
          offset: 12
          size: 30
        subframe_2:
          offset: 42
          size: 30
        subframe_3:
          offset: 72
          size: 30
        crc:
          offset: 102
          size: 4
    47:
      name: psrpos
      fields:
        sol_status:
          offset: 0
          size: 4
    48:
      name: satvis
      fields:
        sat_vis:
          offset: 0
          size: 4
          encode: Bool
        comp_alm:
          offset: 4
          size: 4
        sat_num:
          offset: 8
          size: 4
        prn:
          offset: 12
          size: 2
        glofreq:
          offset: 14
          size: 2
        health:
          offset: 16
          size: 4
        elev:
          offset: 20
          size: 8
        az:
          offset: 28
          size: 8
        true_dop:
          offset: 36
          size: 8
        app_dop:
          offset: 44
          size: 8
    83:
      name: trackstat
      fields:
        sol_status:
          offset: 0
          size: 4
        pos_type:
          offset: 4
          size: 4
        cutoff:
          offset: 8
          size: 4
        num_chans:
          offset: 12
          size: 4
